main:
  params: [input]
  steps:
    - call_function:
        call: http.get
        args:
          url: https://europe-central2-shining-rampart-426818-e1.cloudfunctions.net/air_pollution_function
          auth:
            type: OIDC
        result: function_response