name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: shining-rampart-426818-e1
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


    - name: Authenticate with service account
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' | jq '.' > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json


    - name: Set Project ID
      run: gcloud config set project shining-rampart-426818-e1



    - name: Deploy extract function to Google Cloud Functions
      run: |
        gcloud functions deploy extract_airpollution_function \
        --runtime python311 \
        --trigger-http \
        --entry-point gcloud_get_openweather_data_function \
        --region europe-central2 \
        --source ./gcloud/functions

    - name: Deploy workflow
      run: |
        gcloud workflows deploy AirPollutionWorkflow \
        --location europe-central2 \
        --source ./gcloud/workflows/my_workflow.yaml


    - name: Deploy transform function to Google Cloud Functions
      run: |
        gcloud functions deploy transform_airpollution_function \
        --runtime python311 \
        --trigger-topic AirPollutionTopic \
        --entry-point hello_pubsub \
        --region europe-central2 \
        --source ./gcloud/functions
        --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}