name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: shining-rampart-426818-e1
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


    - name: Authenticate with service account
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' | jq '.' > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json


    - name: Set Project ID
      run: gcloud config set project shining-rampart-426818-e1



    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy air_pollution_function \
        --runtime python311 \
        --trigger-http \
        --entry-point gcloud_get_openweather_data_function \
        --region europe-central2 \
        --source ./

    - name: Deploy workflow
        run: |
          gcloud workflows deploy AirPollutionWorkflow \
          --source my_workflow.yaml